# Generated by Django 4.1.2 on 2022-12-19 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bissex', '0002_alter_bissex_history_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bissex_history',
            new_name='Bissex',
        ),
    ]
