# Generated by Django 4.1.2 on 2022-12-23 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bissex', '0003_rename_bissex_history_bissex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bissex',
            name='command_date',
            field=models.DateTimeField(blank=True, default='23/12/2022 10:18:57', max_length=100),
        ),
    ]
